### ISSUE TITLE
Can not parse openapi spec with recursive references

### ISSUE THREAD

**Issue by hottestseason** [getkin/kin-openapi#309]
It looks this library fail to parse spec which has recursive references like this
https://github.com/hottestseason/kin-openapi/tree/f9ccdc2e69d360c4f17a7c94189526457e90b1f3/openapi3/testdata/recursiveRef

```openapi.yml
openapi: "3.0.3"
info:
  title: Recursive refs example
  version: "1.0"
paths:
  /foo:
    $ref: ./paths/foo.yml
components:
  schemas:
    Foo:
      $ref: ./components/Foo.yml
    Bar:
      $ref: ./components/Bar.yml
```
```paths/foo.yml
get:
  responses:
    "200":
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              foo:
                $ref: ../openapi.yml#/components/schemas/Foo
```
```components/Foo.yml
type: object
properties:
  bar:
    type: array
    items:
      $ref: ../openapi.yml#/components/schemas/Bar
```
```components/Bar.yml
type: string
example: bar
```

It works when loading bundled version such as using `swagger-cli bundle`

**Comment by roee88** [comment]
@fenollp I don't think that this one is fixed.  A minimal example to reproduce:

```yaml
openapi: 3.0.1
info:
  title: Recursive refs example
  version: "1.0"
paths: {}
components:
  schemas:
    Complex:
      type: object
      properties:
        parent:
          $ref: '#/components/schemas/Complex'
```

Should I open a different issue?

**Comment by chrisdostert** [comment]
@fenollp @hottestseason thanks for all the hard work and a the great project. I'm still seeing this as well so I don't think it's fixed yet. The issue I'm hitting is the same as @roee88 's example where my schema is recursive. The result is, golang model generation hangs indefinitely.

**Comment by fenollp** [comment]
Ah sorry I missed that @roee88 
Yes please open a dedicated issue and maybe a PR with the looping snippet.
There are loop detection mechanisms in place and they appear not to handle this kind of code... 
https://github.com/getkin/kin-openapi/blob/e9b36dac1a2890474ae44cfcf6446c00393527b5/openapi3/loader.go#L50

PRs welcomed!
